gray_image_dir: "/home/colin/booth_photos/gray"
color_image_dir: "/home/colin/booth_photos/color"
original_image_dir: "/home/colin/booth_photos/original"
qr_dir: "/home/colin/booth_qrs"
photo_path_db: "/home/colin/booth_photos/photo_db.json"
qr_path_db: "/home/colin/booth_qrs/qr_db.json"
qr_pos: [0, 405, 195, 195]
display_gray: true
display_first_image_time: 45 # Show the captured image for 45 seconds
display_shuffle_time: 30 # Show a new image from the saved ones every 30 seconds
display_timeout: 1200 # Go back to preview after 20 minutes
led_idle_brightness: 15 # normally 15
led_capture_brightness: 100 # normally 100
button_pulse_time: 4
qr_check_time: 0.25 # Interval to check for QR codes
crop_preview: true # normally True
lens_cal_file: "/home/colin/simple_pi_photobooth/lens_cal_v6_fixedar.bin"
continuous_cap: false # Capture photos constantly when in idle state, for debugging
enable_upload: true
color_postfix: "_color"
gray_postfix: "_gray"
smugmug_creds_path: "/home/colin/smugmug.json"
photo_title: ""
photo_caption: "Tap and hold to save!"
album_title_file: "/home/colin/album_title.txt"
contrast: 1.1
