# Backend settings
gray_image_dir: "/home/colin/booth_photos/gray"
color_image_dir: "/home/colin/booth_photos/color"
original_image_dir: "/home/colin/booth_photos/original"
qr_dir: "/home/colin/booth_qrs"
photo_path_db: "/home/colin/booth_photos/photo_db.json"
qr_path_db: "/home/colin/booth_qrs/qr_db.json"
color_postfix: "_color"
gray_postfix: "_gray"
enable_upload: true
smugmug_creds_path: "/home/colin/smugmug.json"
photo_title: ""
photo_caption: "Tap and hold to save!"
request_timeout: 20

# UI settings
qr_pos: [0, 405, 195, 195]
display_gray: true
display_first_image_time: 45 # Show the captured image for 45 seconds
display_shuffle_time: 30 # Show a new image from the saved ones every 30 seconds
display_timeout: 1200 # Go back to preview after 20 minutes
led_idle_brightness: 15 # normally 15
led_capture_brightness: 100 # normally 100
button_pulse_time: 4
wifi_check: true
wifi_check_time: 5 # Interval to check if the wifi is connected
crop_preview: true # normally True
continuous_cap: false # Capture photos constantly when in idle state, for debugging
enable_multi_shot: true
qr_check_time: 0.25 # Interval to check for QR codes

overlays:
    arrow:
        path: "/home/colin/overlays/arrow_v5.png"
        size: [434,150]
        offset: [450,295]
        weight: 0.6
    three_shots:
        path: "/home/colin/overlays/three_shots_v2.png"
        size: [700,100]
        offset: [500,162]
        weight: 0.6

# Photo settings
lens_cal_file: "/home/colin/simple_pi_photobooth/lens_cal_v6_fixedar.bin"
contrast: 1.1
brightness: 0.05
        
# watermark: # EXAMPLE
#    watermark_path: "<path_to_watermark>"
#    weight: 1
#    h_size: 950
#    offset_x: 100
#    offset_y: 90
# album_title: "<your album title>"
