gray_image_dir: "/home/colin/booth_photos/gray"
color_image_dir: "/home/colin/booth_photos/color"
display_gray: true
display_shuffle_time: 30
display_timeout: 1200
led_idle_brightness: 40
led_capture_brightness: 255 # normally 255
button_pulse_time: 5
crop_preview: true # normally True
#lens_cal_file: "/home/colin/simple_pi_photobooth/lens_cal_v4.bin"
