thumbnail_dir: "/home/colin/simple_pi_photobooth/print_kiosk/thumbnails"
photo_dir: "/home/colin/booth_photos_local/"
# These must align with the directory and postfixes in config.yaml used on the Booth Pi
remote_photo_dir: "/home/colin/booth_photos/"
print_postfixes:
    - "_color"
    - "_gray"
h_crop_2x6: 0.9
h_pad: 0.04
mount_addresses:
    - "192.168.1.114"
    - "boothpi"
mount_source: "/home/colin/booth_photos"
splash_image: "/home/colin/kiosk_splash.png"
splash_timeout: 60
#logo_config: # EXAMPLE
#    logo_path: "<path to logo file>"
#    logo_width_scale: 0.6
#    enable: true
print_format: "2x6"
status_file_path: "/home/colin/print_status.json"
status_update_interval: 120